### ISSUE TITLE
Making Pretty Pictures Lab

### ISSUE THREAD

**Issue by kmccabe11** [UOsociology/the-tidyverse-kmccabe11#2]
Completed the lab @AaronGullickson

**Comment by AaronGullickson** [comment]
@kmccabe11 Nice graph! I think the only downside to panelizing here is that you can't exactly tell how much the slopes are changing across maturity rating. It does appear to me that the R-rated slope is a bit lower, but I suspect that is because there is a diminishing return type relationship and only R-rated movies have runtimes >175 minutes. Leaving out `method="lm"` seems to support that idea.
